name: Supermassive

# -------------------------------------------------------
# Configuration.
# -------------------------------------------------------

exclude: ['_sources', '_raws', '.gitignore', '_config.yml', 'run', 'README.md']

show_drafts: nil

permalink: /:categories/:year/:month/:title

paginate_path: 'journal/:num'
paginate: 4

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["tables", "footnotes"]
