name: Supermassive

# -------------------------------------------------------
# Configuration.
# -------------------------------------------------------

exclude: ['.gitignore', '_config.yml', 'run', 'README.md']
permalink: /:categories/:year/:month/:title

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["footnotes"]

# -------------------------------------------------------
# Sass
# -------------------------------------------------------

sass:
  style: :compressed
