name: Supermassive

# -------------------------------------------------------
# Configuration.
# -------------------------------------------------------

exclude: ['.gitignore', 'README.md']
permalink: /:categories/:year/:month/:title

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["footnotes"]

# -------------------------------------------------------
# Sass.
# -------------------------------------------------------

sass:
  style: :compressed

# -------------------------------------------------------
# Front-matter defaults.
# -------------------------------------------------------

defaults:
  -
    scope:
      path: ''
    values:
      layout: default
