name: Steredenn

# -------------------------------------------------------
# Configuration.
# -------------------------------------------------------

include: ['_pages']
exclude: ['.gitignore', 'README.md', 'deploy', 'run', 'Gemfile', 'Gemfile.lock']
permalink: /:categories/:year/:month/:title/

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["footnotes"]

# -------------------------------------------------------
# Sass.
# -------------------------------------------------------

sass:
  style: :compressed

gems:
  - jekyll-coffeescript
