#!/usr/bin/env bash

BASEDIR=$(dirname $0)
cd $BASEDIR

source .env

# --------------------------------------------------------------
# Get destination.
# --------------------------------------------------------------

if [ "$1" ]; then
  DESTINATION=$1
else
  DESTINATION="$SERVER_NAME"
fi

if [ -z "$DESTINATION" ]; then
  echo "Error: no destination provided (as .env variable or argument)."
  exit 1
fi

# --------------------------------------------------------------
# Deploy.
# --------------------------------------------------------------

bundle exec jekyll build

rsync -vaz _site/ $DESTINATION:/var/www/steredenn-classic

ssh $DESTINATION 'service nginx restart'

rm -rf _site
