#!/bin/bash

DESTINATION=$1

if [ -z "$DESTINATION" ]; then
  echo "Error: no user@server argument. Abort..."
  exit 0
fi

jekyll build
scp -r _site $DESTINATION:/var/www/

ssh $DESTINATION 'cd /var/www/ && \
                  rm -rf supermassive.pixelnest.io && \
                  mv _site supermassive.pixelnest.io && \
                  service nginx restart'
